- name: Ensure Apache is installed
  ansible.builtin.yum:
    name: httpd
    state: present
  become: true

- name: Ensure Apache service is enabled and running
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started
  become: true
  #notify: restart apache
